site_name: Office Manual
site_url: https://jadesunriselaw.netlify.app/
copyright: Copyright &copy; 2023 Jade Sunrise Law

nav:
  - Real Estate:
      - Clients Classroom:
          - FAQ: realestate/faq.md
          - Joint Ownership: realestate/joint.md
          - What's Title Insurance: realestate/titleinsure.md
      - Email Templates:
          - Fee Quotations: realestate/email-quotation.md
          - First Email to clients: realestate/email-1.md
      - Common Issues at Closing:
          - Air Conditioning Unit On RPR: realestate/acrpr.md
          - New Condo Expedited Registration: realestate/newCondoReg.md
          - Out of Province Signing Instruction: realestate/ops.md
          - Special Formality of Remote Signing: realestate/remotesign.md
      - Conveyancing Docs List: realestate/docu-list.md
      - RPR Checklist: realestate/rpr-checklist.md
      - Deal To Do list: realestate/deal-checklist.md
      - Land Usage Search: realestate/usage.md
      - Banks' Contact Info: realestate/bankcontact-new.md
  - Corporate:
      - Prepare Initial Minute Book: corporate/minbook.md
      - Minute Book of Share Transfer: corporate/minbook-2.md
      - Incorporate an Alberta Corporation: corporate/2024-03-01-Incorporate.md
  - Family and Wills:
      - Why We Need a Will: family/will-important.md
      - How to Pick Your Will Executor: family/willDirector.md
  - Notary Services:
      - Procedure and Fees: notary/notary-apostille.md
      - Judicial Delivery: notary/HagueService.md
  # - Immigration:
  #     - Front Page: immigration/crs.md
  - Others:
      - Fees:
          - Real Estate Fees and Disbursements: fees/real-estate.md
          # - Notary Service Quotation: fees/notary.md
          - Will Quotation: fees/willfee.md
          - Corporate Services: fees/corporateFee.md
          - Immigration:
              - PNP&#58 Rural Entrepreneur Stream: fees/res-fees.md
              - Spouse Sponsorship: fees/prss-fees.md
              - LMIA and Work Permit: fees/lmia-wp-fees.md
          - Hourly Rate 2024: fees/hourlyRate.md
      - Accounts: others/accounts.md
      - Searches: others/searches.md
      - Credit Card: others/2024-03-01-creditCard.md
  - About:
      - Office Manual: index.md
      # - Staff Manual: about/manual.md
      # - Disclaimer: about/disclaimer.md

theme:
  name: material

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      # scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  language: en

  logo: jade_logo.png
  favicon: jade_logo.png

  features:
    - navigation.instant # without fully reloading the page, fast loading function
    - navigation.tracking
    - navigation.tabs #top-level sections are rendered in a menu layer below the header
    # - navigation.tabs.sticky
    # - navigation.sections
    - navigation.path
    # - navigation.indexes ##enable it if you have an introduction to top level
    - navigation.top
    - header.autohide
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://github.com/@
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/@
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/@
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@jadesunriselaw.com
  generator: false

plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - assets/css/styled-table.css
  # - https://unpkg.com/leaflet@1.9.4/dist/leaflet.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css
  - assets/css/icon.css

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
