site_name: 顶誉法律资料库
site_url: https://jadesunriselaw.netlify.app/
copyright: 版权所有 &copy; 2023 顶誉律师行

nav:
  - 房屋买卖:
      - 共有产权的类型: realestate/joint.md
      - 什么是产权保险: realestate/titleinsure.md
      - 常见问题答复: realestate/faq.md
  - 婚姻/遗嘱:
      - 1: index.md
  - 律师公证:
      - 公证业务简介: notary/intro.md
  - 留学移民:
      - 1: index.md
  - 收费公示:
      - 房地产交易律师收费标准: fees/real-estate.md
      - 公证业务收费标准: fees/notary.md
  - 本所地址: address.md

theme:
  name: material

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      # scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  language: zh

  logo: jade_logo.png
  favicon: jade_logo.png

  features:
    - navigation.instant # without fully reloading the page, fast loading function
    - navigation.tracking
    - navigation.tabs #top-level sections are rendered in a menu layer below the header
    # - navigation.tabs.sticky
    # - navigation.sections
    - navigation.path
    # - navigation.indexes ##enable it if you have an introduction to top level
    - navigation.top
    - header.autohide
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://github.com/@
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/@
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/@
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@jadesunriselaw.com
  generator: false

plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
